version: '3'
services:
 webapp:
  build:
   context: .
   dockerfile: Dockerfile
  ports:
   - "8100:8080"
  volumes:
   - appdata:/var/local/tomcat
  networks:
   - user_network



volumes:
 appdata:

networks:
 user_network:
